name: time-series-methods
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
    - aeon==0.11.0
    - jupyter-contrib-nbextensions
    - jupyter-nbextensions-configurator